const fs = require('fs');
const path = require('path');

function generateIndex(targetIndexFile, recursive = true) {
  const targetDir = path.dirname(targetIndexFile);
  const exports = [];

  function walk(dir) {
    if (!fs.existsSync(dir)) {
      return;
    }
    const files = fs.readdirSync(dir);
    for (const file of files) {
      const fullPath = path.join(dir, file);
      const stat = fs.statSync(fullPath);

      if (stat.isDirectory()) {
        if (recursive) {
          walk(fullPath);
        }
      } else if (file.endsWith('.ts')) {
        // Skip the main index.ts file we are generating
        if (path.resolve(fullPath) === path.resolve(targetIndexFile)) {
          continue;
        }

        // Remove nested index.ts files to keep imports clean
        if (file === 'index.ts') {
          console.log(`Deleting redundant nested index: ${fullPath}`);
          try {
            fs.unlinkSync(fullPath);
          } catch (err) {
            console.error(`Failed to delete ${fullPath}:`, err.message);
          }
          continue;
        }

        // Compute and format the relative path for TypeScript imports
        let relativePath = path.relative(targetDir, fullPath);
        relativePath = relativePath.replace(/\\/g, '/').slice(0, -3);

        if (!relativePath.startsWith('./') && !relativePath.startsWith('../')) {
          relativePath = './' + relativePath;
        }

        exports.push(`export * from '${relativePath}';`);
      }
    }
  }

  walk(targetDir);
  exports.sort();

  const content = [
    '// Auto-generated by container script. Do not edit manually.',
    ...exports,
    ''
  ].join('\n');

  // Skip writing if the content is unchanged to prevent redundant build triggers
  if (fs.existsSync(targetIndexFile)) {
    const existingContent = fs.readFileSync(targetIndexFile, 'utf8');
    if (existingContent === content) {
      return;
    }
  }

  fs.writeFileSync(targetIndexFile, content, 'utf8');
  console.log(`Updated index file: ${targetIndexFile} with ${exports.length} exports.`);
}

// Generate index for filters
generateIndex('./filters/index.ts', true);

// Watch for modifications if `--watch` flag is provided
if (process.argv.includes('--watch')) {
  console.log('Watching for file changes in ./filters...');
  
  let debounceTimeout = null;
  const watchDir = './filters';

  fs.watch(watchDir, { recursive: true }, (eventType, filename) => {
    if (filename && (filename.endsWith('.ts') || filename.endsWith('index.ts'))) {
      if (debounceTimeout) {
        clearTimeout(debounceTimeout);
      }
      debounceTimeout = setTimeout(() => {
        try {
          generateIndex('./filters/index.ts', true);
        } catch (err) {
          console.error('Error regenerating index:', err.message);
        }
      }, 300);
    }
  });
}